name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: '20'

jobs:
  # Speeds up CI
  install:
    runs-on: ubuntu-latest
    steps:
      # Gets access to code from repository
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        # Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Cache client dependencies
        id: cache-client
        uses: actions/cache@v4
        with:
          path: client/node_modules
          # Cache dependencies and save with key
          key: Linux-client-${{ hashFiles('client/package-lock.json') }}

      # Installs dependencies only if not installed
      - name: Install client dependencies
        if: steps.cache-client.outputs.cache-hit != 'true'
        run: |
          cd client
          npm ci

      - name: Cache backend dependencies
        id: cache-backend
        uses: actions/cache@v4
        with:
          path: server/node_modules
          key: Linux-client-${{ hashFiles('backend/package-lock.json') }}

      # Installs dependencies only if not installed
      - name: Install backend dependencies
        if: steps.cache-backend.outputs.cache-hit != 'true'
        run: |
          cd server
          npm ci

      # Uploads cache to access dependencies in other jobs 
      - name: Upload dependencies cache
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: |
            client/node_modules
            server/node_modules

  test:
    runs-on: ubuntu-latest
    # Needs to dependencies to be installed first
    needs: install
    steps:
      # Gets access to code from repository
      - uses: actions/checkout@v4

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: node-modules

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Run tests for backend
        run: |
          cd client
          npm run test

  type-check:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: node-modules

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Type check backend
        run: |
          cd server
          npm run type-check

      - name: Type check frontend
        run: |
          cd client
          npm run type-check

  build:
    runs-on: ubuntu-latest
    needs: [install, test, type-check]
    steps:
      - uses: actions/checkout@v4
     
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: node-modules

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build client
        run: |
          cd client
          npm run build
      
      - name: Build server
        run: |
          cd server
          npm run build
          
